### ISSUE TITLE
Installing Frost from PyPi fails

### ISSUE THREAD

**Issue by sciurus** [mozilla/frost#396]
In a fresh virtualenv, installing from from pypi fails:

```
(frost-pypi) bpitts39260:frost bpitts$ pip install frost
Collecting frost
  Downloading frost-0.4.0.tar.gz (51 kB)
     |████████████████████████████████| 51 kB 1.0 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/bpitts/.virtualenvs/frost-pypi/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nl/16g8k8154b38h279xxpx9vqm0000gn/T/pip-install-8om96jag/frost/setup.py'"'"'; __file__='"'"'/private/var/folders/nl/16g8k8154b38h279xxpx9vqm0000gn/T/pip-install-8om96jag/frost/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/nl/16g8k8154b38h279xxpx9vqm0000gn/T/pip-pip-egg-info-ucnqav8q
         cwd: /private/var/folders/nl/16g8k8154b38h279xxpx9vqm0000gn/T/pip-install-8om96jag/frost/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/nl/16g8k8154b38h279xxpx9vqm0000gn/T/pip-install-8om96jag/frost/setup.py", line 10, in <module>
        line.split("==")[0] for line in open("requirements.txt", "r") if ".git" not in line
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the '/Users/bpitts/.virtualenvs/frost-pypi/bin/python -m pip install --upgrade pip' command.
```

**Comment by sciurus** [comment]
@Micheletto you were saying that this worked for you?
